### PR TITLE
[Fix] Replace `semver` (uses node builtin libs) with `compare-versions` (pure javascript)

### LINKED ISSUE #835: Cloudflare Pages - Wrangler fails with `semver` due to Node built-in lib dependency
# Issue summary

While using Wrangler for Cloudflare Pages (`wrangler pages dev` command), with `@shopify/shopify-api` dependency and using them in routes, fails with NodeJS built-in package dependency.

- `@shopify/shopify-api` version: `7.0.0`
- Node version: `v16.19.1`
- Operating system: `macOS`
- Wrangler CLI version: `2.16.0`

```
Compiling worker to "/var/folders/4f/h9qykpcd3pbcbnccyql7bf_m0000gn/T/functionsWorker-0.6486551827953275.mjs"...
✘ [ERROR] 1 error(s) and 0 warning(s) when compiling Worker.


✘ [ERROR] Could not resolve "util"

    ../node_modules/semver/classes/semver.js:19:54:
      19 │ ... TypeError(`Invalid Version: ${require('util').inspect(version)}`)
         ╵                                           ~~~~~~

  The package "util" wasn't found on the file system but is built into node.
  Add "node_compat = true" to your wrangler.toml file to enable Node compatibility.


✘ [ERROR] Build failed with 1 error:

  ../node_modules/semver/classes/semver.js:19:54: ERROR: Could not resolve "util"


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Expected behavior

The `@shopify/shopify-api` package should not depend on NodeJS built-in libs via dependencies.

## Actual behavior

Replace `semver` (which is `node-semver`) with pure JavaScript for consumption in any JavaScript runtime.

## Steps to reproduce the problem

1. Add `@shopify/shopify-api` to Cloudflare Pages project
2. Include `import "@shopify/shopify-api/adapters/cf-worker";`
3. Start `wrangler pages dev` and observe the error

### PR DESCRIPTION
**Pull request by anselm94**
### WHY are these changes introduced?

Fixes #835 

Replaced [`semver`](https://www.npmjs.com/package/semver) package which had NodeJS built-in libs with [`compare-versions`](https://www.npmjs.com/package/compare-versions) package which is a pure JavaScript implementation.

### WHAT is this pull request doing?

Replaces `semver` package occurrences with `compare-versions` to reduce dependency on NodeJS built-in libs. Kept the naming intact for easier readability.

## Type of change

- [x] Patch: Bug (non-breaking change which fixes an issue)

## Checklist

- [x] I have used `yarn changeset` to create a draft changelog entry (do NOT update the `CHANGELOG.md` file manually)
- [x] I have added/updated tests for this change
- ~I have documented new APIs/updated the documentation for modified APIs (for public APIs)~ Not applicable

### CODE REVIEW

File: lib/logger/index.ts [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import semver from 'semver';
+import {compare as semver} from 'compare-versions';
```
Comment (mkevinosullivan) [inline lib/logger/index.ts:1]:
```suggestion
import {compare} from 'compare-versions';
```

File: lib/setup-jest.ts [hunk 2]
```diff
@@ -1,4 +1,4 @@
-import semver from 'semver';
+import {compare as semver} from 'compare-versions';
```
Comment (mkevinosullivan) [inline lib/setup-jest.ts:1]:
```suggestion
import {compare} from 'compare-versions';
```

File: lib/setup-jest.ts [hunk 3]
```diff
@@ -131,7 +131,7 @@ expect.extend({
     return {
       message: () =>
         `Found deprecation limited to version ${version}, please update or remove it.`,
-      pass: semver.lt(SHOPIFY_API_LIBRARY_VERSION, version),
+      pass: semver(SHOPIFY_API_LIBRARY_VERSION, version, '<'),
```
Comment (mkevinosullivan) [inline lib/setup-jest.ts:134]:
```suggestion
      pass: compare(SHOPIFY_API_LIBRARY_VERSION, version, '<'),
```

File: lib/utils/versioned-codeblocks.ts [hunk 4]
```diff
@@ -1,9 +1,9 @@
-import semver from 'semver';
+import {compare as semver} from 'compare-versions';
```
Comment (mkevinosullivan) [inline lib/utils/versioned-codeblocks.ts:1]:
```suggestion
import {compare} from 'compare-versions';
```

File: lib/utils/versioned-codeblocks.ts [hunk 5]
```diff
@@ -1,9 +1,9 @@
...
 
 import {SHOPIFY_API_LIBRARY_VERSION} from '../version';
 
 export function enableCodeAfterVersion(version: string, fn: () => void): void {
-  if (semver.gte(SHOPIFY_API_LIBRARY_VERSION, version)) {
+  if (semver(SHOPIFY_API_LIBRARY_VERSION, version, '>=')) {
```
Comment (mkevinosullivan) [inline lib/utils/versioned-codeblocks.ts:6]:
```suggestion
  if (compare(SHOPIFY_API_LIBRARY_VERSION, version, '>=')) {
```

File: package.json [hunk 6]
```diff
@@ -75,11 +75,9 @@
   },
   "dependencies": {
     "@shopify/network": "^3.2.1",
-    "@types/node-fetch": "^2.5.7",
-    "@types/supertest": "^2.0.10",
+    "compare-versions": "^6.0.0-rc.1",
```
Comment (mkevinosullivan) [inline package.json:78]: Prefer to use latest stable release rather than a release candidate ... we can update it later once `6.0.0` has been released.
```suggestion
    "compare-versions": "^5.0.3",
```

**Review by mkevinosullivan — CHANGES_REQUESTED** [review]
Thank you so much for identifying this issue and providing the fix ... very much appreciated.

**Comment by anselm94** [comment]
Thanks @mkevinosullivan for the feedback :)

**Review by mkevinosullivan — APPROVED** [review]
